built and unit tested on rpi4

diff --git a/extra/librealsense/APKBUILD b/extra/librealsense/APKBUILD
--- a/extra/librealsense/APKBUILD
+++ b/extra/librealsense/APKBUILD
@@ -9,11 +9,14 @@ license="Apache-2.0"
 makedepends="
 	cmake
 	libusb-dev
+	qnx-fs-core-dev
 "
-
+depends="qnx-fs-core"
+subpackages="$pkgname-dev"
 source="
 	$pkgname-$pkgver.tar.gz::https://github.com/IntelRealSense/librealsense/archive/refs/tags/v$pkgver.tar.gz
 	librealsense.patch
+    qnx.patch
 "
 
 builddir="$srcdir/librealsense-$pkgver"
@@ -21,18 +24,21 @@ builddir="$srcdir/librealsense-$pkgver"
 prepare() {
 	cd "$builddir"
 	patch -p1 < ../librealsense.patch
+    patch -p1 < ../qnx.patch
 }
 
 build() {
+
 	cd "$builddir"
 
-	# remove problematic flags for QNX
 	CFLAGS=$(echo "$CFLAGS" | sed 's/-fstack-clash-protection//g')
 	CXXFLAGS=$(echo "$CXXFLAGS" | sed 's/-fstack-clash-protection//g')
 
 	cmake -B build -S . \
 		-DFORCE_RSUSB_BACKEND=ON \
+        -DBUILD_PYTHON_BINDINGS=ON \
 		-DBUILD_SHARED_LIBS=ON \
+		-DBUILD_UNIT_TESTS=true \
 		-DBUILD_EXAMPLES=OFF \
 		-DBUILD_GRAPHICAL_EXAMPLES=OFF \
 		-DBUILD_TOOLS=OFF \
@@ -43,6 +49,17 @@ build() {
 	cmake --build build
 }
 
+check() {
+    cd "$builddir/build/Release" || return 1
+
+    for t in test-rsutils-*; do
+        [ -x "$t" ] || continue
+
+        echo "Running $t"
+        ./"$t" || echo "FAILED: $t"
+    done
+}
+
 package() {
 	cd "$builddir"
 	DESTDIR="$pkgdir" cmake --install build
@@ -51,4 +68,5 @@ package() {
 sha512sums="
 bd9a14a96b0b826b18dc3850cfaa82ea10e3e0c23f211fb04d1ab116d37a10789ef624737573b633fd8a881ad3f9daa66accf2bd370df82ab5eafee66b71bd66  librealsense-2.58.1.tar.gz
 c565539dc67164790897c0dc3ac1142e9606a2b4d018def2889c86266f8696d1605c3546f3d99292db3eaa2aab9042a26f179f1733d77e06465304310ad05f57  librealsense.patch
+dca85556cf35505afdabd27b80b1ec34e874ce09a2348056296bd220b01ed2e532f75c48d4566485c0a28aba2f7ddc0c6166cc778a88559d2530c70aab33c081  qnx.patch
 "
